import { NextRequest, NextResponse } from "next/server";
import prisma from "@/lib/db";

export async function POST(
    req: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    const { id } = await params;
    const plan = await prisma.auditPlan.findUnique({ where: { id } });

    if (!plan) return NextResponse.json({ error: "Plan not found" }, { status: 404 });

    const evidence = (plan.evidencePlan as any[]) || [];

    // Generate PBC (Provided By Client) Index as Markdown
    let markdown = `# PBC Index - ${plan.framework} Audit (${plan.auditType})\n`;
    markdown += `**Period:** ${plan.startDate} to ${plan.endDate}\n\n`;
    markdown += `| ID | Evidence Category | Item Description | Collection | Owner |\n`;
    markdown += `|----|-------------------|------------------|------------|-------|\n`;

    evidence.forEach((item, idx) => {
        markdown += `| PBC-${idx + 1} | ${item.category} | ${item.evidenceItem} | ${item.collectionMethod} | ${item.ownerRole} |\n`;
    });

    markdown += `\n\nGenerated by Certixo AI Auditor on ${new Date().toLocaleDateString()}`;

    return new NextResponse(markdown, {
        headers: {
            "Content-Type": "text/markdown",
            "Content-Disposition": `attachment; filename="PBC_Index_${id}.md"`
        }
    });
}
